### ISSUE TITLE
Make the Boards Side by Side

### ISSUE THREAD

**Issue by alfayeza** [OSU-CS361-W17/group22_project2#11]
Place the boards side by side, instead of one above another. Makes it easy to keep track of the game as the user doesn't have to scroll down every time he wanted to compare his board with the opponent's board.

**Comment by munishaparikh** [comment]
Yup true
Doing that and adding the aircraft submarines and all

**Comment by munishaparikh** [comment]
I'm just adding  the ships

**Comment by alfayeza** [comment]
Yeah it will look much better. Don't forget to move "theirs" too!

**Comment by munishaparikh** [comment]
Move?

**Comment by TheDragonMeister** [comment]
has this been finished? if so we should close the issue

**Comment by munishaparikh** [comment]
I think everything's done
