### ISSUE TITLE
3 different designs

### ISSUE THREAD

**Issue by khaneh321** [OSU-CS361-W17/group22_project2#3]
I'm posting my design ideas in the Wiki! I've decided to keep them really simple as we don't have much time left for implementation. Will show you guys my sketches in class tomorrow.

**Comment by khaneh321** [comment]
I'm turning in my designs on paper tomorrow, but have mentioned what they are in the wiki so we can vote.

**Comment by TheDragonMeister** [comment]
okay awesome looks like we have all finsihed this i am closing the issue
